"""Protocolo que debe cumplir cualquier renderer de chat."""
from __future__ import annotations

from typing import Protocol, runtime_checkable

from core.tool_result import ToolResult


@runtime_checkable
class ChatRenderer(Protocol):
    @property
    def response_text(self) -> str: ...

    @property
    def response_start(self) -> int | None: ...

    def reset(self) -> None: ...
    def reset_response_segment(self) -> None: ...
    def insert_user_message(self, text: str) -> None: ...
    def on_text(self, text: str) -> None: ...
    def insert_narration(self, text: str, active: bool = False) -> None: ...
    def insert_tool_card(self, result: ToolResult) -> None: ...
    def insert_error(self, message: str) -> None: ...
    def final_text(self, fallback: str) -> str: ...
    def restore_assistant_message(self, text: str) -> None: ...
    def remove_from_last_user(self) -> None: ...