"""Protocolo que debe cumplir cualquier renderer de chat."""
from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class ChatRenderer(Protocol):
    @property
    def response_text(self) -> str: ...

    @property
    def response_start(self) -> int | None: ...

    def reset(self) -> None: ...
    def reset_response_segment(self) -> None: ...
    def insert_user_message(self, text: str) -> None: ...
    def on_text(self, text: str) -> None: ...
    def insert_tool_event(self, text: str, color: str) -> None: ...
    def insert_tool_result(self, text: str) -> None: ...
    def insert_error(self, message: str) -> None: ...
